# Site settings
title: Khushkaran Singh Bajwa
short_title: K S Bajwa
email: khushkaran@users.noreply.github.com
description: "My name is Khushkaran, I am a Software Engineer at OLM Systems in Derby."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 70B8FF #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ks1ngh
  - title: github
    url: http://github.com/khushkaran
  - title: bitbucket 
    url: http://bitbucket.org/khushkaran
  - title: stack-overflow
    url: http://stackoverflow.com/story/khushkaran

# Postal address (add as many lines as necessary)
address:
  - line: Working & living in Derby, England.

# Build settings
markdown: kramdown
permalink: pretty
